import type { ElementKind, HouseElement, HouseProject, LayerName, Level, MaterialKey, ProjectCheck, QuantityRow, Room, SiteSettings, Vec3 } from "@/types/houseforge";

const storeKey = "houseforge-project-v1";

export const materialColors: Record<MaterialKey, string> = { rcc: "#7f8987", concrete: "#77807c", brick: "#895f49", aac: "#c9c5b7", steel: "#586f76", wood: "#936b4d", glass: "#8fc7cb", tile: "#aeb9b4", marble: "#cbc9bf", plaster: "#d8d2c4", paint: "#becdbb", grass: "#5f7d54", asphalt: "#2c3639" };
export const layerFor: Record<ElementKind, LayerName> = { foundation: "foundation", wall: "architecture", column: "structure", beam: "structure", slab: "structure", door: "openings", window: "openings", stair: "architecture", roof: "roof", furniture: "interior", plumbing: "mep", electrical: "mep", hvac: "mep", landscape: "landscape", finish: "architecture" };
export const structuralKinds: ElementKind[] = ["foundation", "column", "beam", "slab"];
export const defaultCorners = (width: number, length: number) => [{ x: -width / 2, z: -length / 2 }, { x: width / 2, z: -length / 2 }, { x: width / 2, z: length / 2 }, { x: -width / 2, z: length / 2 }];
export function siteAssetPlacement(site: Pick<SiteSettings,"road"|"width"|"length">, label: string, dimensions: Vec3): { position: Vec3; rotation: Vec3 } { const alongZ=site.road==="north"||site.road==="south";const sign=site.road==="south"||site.road==="west"?-1:1;const edge=(alongZ?site.length:site.width)/2*sign;const isRoad=/road edge/i.test(label);const isBoundary=/(gate|fence|compound wall)/i.test(label);const offset=isRoad?sign*1.2:isBoundary?0:-sign*1.35;const y=isBoundary?dimensions[1]/2:Math.max(.03,dimensions[1]/2);return { position:alongZ?[0,y,edge+offset]:[edge+offset,y,0], rotation:alongZ||!isBoundary?[0,0,0]:[0,Math.PI/2,0] }; }
export function nearestWallIntersection(start: { x: number; z: number }, end: { x: number; z: number }, elements: HouseElement[]) { const rx=end.x-start.x,rz=end.z-start.z;let nearest:{x:number;z:number;t:number}|undefined;elements.filter((element)=>element.kind==="wall").forEach((wall)=>{const half=wall.dimensions[0]/2,cos=Math.cos(wall.rotation[1]),sin=Math.sin(wall.rotation[1]);const a={x:wall.position[0]-cos*half,z:wall.position[2]-sin*half},b={x:wall.position[0]+cos*half,z:wall.position[2]+sin*half};const sx=b.x-a.x,sz=b.z-a.z,denominator=rx*sz-rz*sx;if(Math.abs(denominator)<.0001)return;const qx=a.x-start.x,qz=a.z-start.z,t=(qx*sz-qz*sx)/denominator,u=(qx*rz-qz*rx)/denominator;if(t>.001&&t<.999&&u>.001&&u<.999&&(!nearest||t<nearest.t))nearest={x:start.x+t*rx,z:start.z+t*rz,t};});return nearest&&{x:nearest.x,z:nearest.z}; }
export function detectAxisAlignedRoom(elements: HouseElement[]) { const walls=elements.filter((element)=>element.kind==="wall");const horizontal=walls.filter((wall)=>Math.abs(Math.sin(wall.rotation[1]))<.15),vertical=walls.filter((wall)=>Math.abs(Math.cos(wall.rotation[1]))<.15);if(horizontal.length<2||vertical.length<2)return;const top=horizontal.reduce((best,wall)=>wall.position[2]<best.position[2]?wall:best),bottom=horizontal.reduce((best,wall)=>wall.position[2]>best.position[2]?wall:best),left=vertical.reduce((best,wall)=>wall.position[0]<best.position[0]?wall:best),right=vertical.reduce((best,wall)=>wall.position[0]>best.position[0]?wall:best);const width=right.position[0]-left.position[0],length=bottom.position[2]-top.position[2];if(width<1||length<1||top.dimensions[0]<width-.3||bottom.dimensions[0]<width-.3||left.dimensions[0]<length-.3||right.dimensions[0]<length-.3)return;return {x:left.position[0],z:top.position[2],width,length}; }
export function propagateLevelElevations(levels: Level[]): Level[] { return levels.map((level,index)=>index===0?level:{...level,elevation:Number((levels[index-1]!.elevation+levels[index-1]!.floorHeight).toFixed(3))}); }
export function reconcileProjectRelationships(project: HouseProject): HouseProject { const walls=new Map(project.elements.filter((item)=>item.kind==="wall").map((item)=>[item.id,item]));const levels=new Map(project.levels.map((level)=>[level.id,level]));return {...project,elements:project.elements.map((element)=>{if((element.kind==="door"||element.kind==="window")&&element.openingFor){const wall=walls.get(element.openingFor);if(!wall)return {...element,openingFor:undefined,openingOffset:undefined,notes:`${element.notes??element.name} · host wall removed`};const openingOffset=Math.max(-Math.max(0,wall.dimensions[0]/2-element.dimensions[0]/2-.05),Math.min(Math.max(0,wall.dimensions[0]/2-element.dimensions[0]/2-.05),element.openingOffset??0));const y=element.kind==="door"?element.dimensions[1]/2:Math.min(wall.dimensions[1]-element.dimensions[1]/2-.1,Math.max(element.dimensions[1]/2+.15,element.position[1]));return {...element,openingOffset,position:[wall.position[0]+Math.cos(wall.rotation[1])*openingOffset,y,wall.position[2]+Math.sin(wall.rotation[1])*openingOffset],rotation:[wall.rotation[0],wall.rotation[1],wall.rotation[2]]};}if(element.kind==="stair"&&element.stairToLevelId){const from=levels.get(element.levelId),to=levels.get(element.stairToLevelId);if(!from||!to||to.elevation<=from.elevation+.2)return {...element,stairToLevelId:undefined,notes:`${element.notes??element.name} · destination level unavailable`};const height=Number((to.elevation-from.elevation).toFixed(3)),risers=Math.max(1,Math.ceil(height/.165)),depth=Math.max(2.5,Number((risers*.27).toFixed(2)));return {...element,dimensions:[element.dimensions[0],height,depth],position:[element.position[0],from.elevation+height/2,element.position[2]],notes:`${element.name} · ${risers} risers at ${Math.round(height/risers*1000)} mm · 270 mm tread`};}return element;})}; }
export const dimensionsFor: Record<ElementKind, Vec3> = { foundation: [1.4, 0.45, 1.4], wall: [4, 3, 0.15], column: [0.35, 3.2, 0.35], beam: [4, 0.35, 0.3], slab: [4, 0.18, 4], door: [1, 2.1, 0.08], window: [1.5, 1.2, 0.08], stair: [2, 1.65, 3], roof: [5, 0.28, 4], furniture: [1.8, 0.8, 0.9], plumbing: [0.35, 0.35, 0.35], electrical: [0.18, 0.18, 0.08], hvac: [0.9, 0.35, 0.25], landscape: [1, 1.8, 1], finish: [3, 0.04, 3] };
export const materialsFor: Record<ElementKind, MaterialKey> = { foundation: "rcc", wall: "brick", column: "rcc", beam: "rcc", slab: "rcc", door: "wood", window: "glass", stair: "rcc", roof: "steel", furniture: "wood", plumbing: "steel", electrical: "paint", hvac: "steel", landscape: "grass", finish: "tile" };

export function id(prefix: string) { return `${prefix}-${Date.now()}-${Math.floor(Math.random() * 999)}`; }
export function createElement(kind: ElementKind, levelId: string, position: Vec3 = [0, 0, 0]): HouseElement { const dimensions = dimensionsFor[kind]; return { id: id(kind), kind, name: `${kind[0].toUpperCase()}${kind.slice(1)} ${Math.floor(Math.random() * 90 + 10)}`, levelId, position, rotation: [0, 0, 0], dimensions: [...dimensions] as Vec3, material: materialsFor[kind], layer: layerFor[kind], structural: structuralKinds.includes(kind) }; }
export function createRoom(name: string, levelId: string, x = 0, z = 0, width = 4, length = 3.6): Room { return { id: id("room"), name, levelId, x, z, width, length, height: 3, floorMaterial: "tile", wallFinish: "Warm white" }; }

const baseLayers: HouseProject["layers"] = { site: { visible: true, locked: false }, architecture: { visible: true, locked: false }, structure: { visible: true, locked: false }, foundation: { visible: true, locked: false }, openings: { visible: true, locked: false }, roof: { visible: true, locked: false }, interior: { visible: true, locked: false }, mep: { visible: true, locked: false }, landscape: { visible: true, locked: false }, dimensions: { visible: true, locked: false } };
export function defaultProject(empty = false): HouseProject {
  const ground: Level = { id: "level-ground", name: "Ground Floor", elevation: 0, floorHeight: 3.3, slabThickness: 0.15, ceilingHeight: 2.9 };
  if (empty) return { name: "Untitled Residential Study", description: "", author: "Atharv Moon", createdAt: Date.now(), units: "metric", site: { width: 12, length: 18, road: "south", north: 0, gridSpacing: 1, snapEnabled: true, workflowMode: "precision", shape: "rectangle", corners: defaultCorners(12, 18), gate: true, sky: "clear", terrain: "level", terrainTool: "level", sunDirection: 135, setbacks: { front: 3, rear: 2, left: 1.5, right: 1.5 }, soil: "medium", bearingCapacity: 150, groundwater: 3 }, assumptions: { houseType: "Residential", structuralSystem: "RCC Frame" }, levels: [ground], rooms: [], elements: [], layers: structuredClone(baseLayers), updatedAt: Date.now() };
  const rooms = [createRoom("Living Room", ground.id, -1.3, -3.2, 4.2, 4), createRoom("Dining", ground.id, 3, -2.7, 3.4, 3), createRoom("Kitchen", ground.id, 3, 1.2, 3.4, 3), createRoom("Master Bedroom", ground.id, -1.4, 2.1, 4.4, 3.8), createRoom("Bath", ground.id, 3.8, 4, 2, 2)];
  const elements: HouseElement[] = [];
  [[-4,-5.2],[4,-5.2],[-4,5.2],[4,5.2]].forEach(([x,z]) => { elements.push(createElement("foundation", ground.id, [x, 0.22, z])); elements.push(createElement("column", ground.id, [x, 1.8, z])); });
  [[0,3.6,-5.2],[0,3.6,5.2],[-4,3.6,0],[4,3.6,0]].forEach(([x,y,z], index) => { const beam = createElement("beam", ground.id, [x,y,z]); beam.rotation = index < 2 ? [0,0,0] : [0,Math.PI/2,0]; beam.dimensions = index < 2 ? [8,0.35,0.3] : [10.4,0.35,0.3]; elements.push(beam); });
  [[0,1.5,-5.1,8,3,0.18],[0,1.5,5.1,8,3,0.18],[-3.9,1.5,0,10,3,0.18],[3.9,1.5,0,10,3,0.18],[-0.3,1.5,0,0.18,3,10]].forEach(([x,y,z,width,height,depth]) => { const wall = createElement("wall", ground.id, [x,y,z]); wall.dimensions=[width,height,depth]; elements.push(wall); });
  const door = createElement("door", ground.id, [0,1.05,-5.22]); elements.push(door); const window = createElement("window", ground.id, [-2.2,1.75,-5.22]); elements.push(window); const slab = createElement("slab", ground.id, [0,3.78,0]); slab.dimensions=[8,0.18,10.4]; elements.push(slab); const roof = createElement("roof", ground.id,[0,4.2,0]); roof.dimensions=[8.6,0.3,11]; elements.push(roof); const stair = createElement("stair",ground.id,[1,0.8,0.8]); elements.push(stair); const sofa = createElement("furniture",ground.id,[-1.5,0.42,-2]); sofa.name="Living sofa"; elements.push(sofa); const tree = createElement("landscape",ground.id,[-5,0.9,-6]); tree.name="Shade tree"; elements.push(tree);
  return { name: "Courtyard Residence", description: "A coordinated editable courtyard residence.", author: "Atharv Moon", createdAt: Date.now(), units: "metric", site: { width: 12, length: 18, road: "south", north: 0, gridSpacing: 1, snapEnabled: true, workflowMode: "precision", shape: "rectangle", corners: defaultCorners(12, 18), gate: true, sky: "clear", terrain: "gentle", terrainTool: "smooth", sunDirection: 135, setbacks: { front: 3, rear: 2, left: 1.5, right: 1.5 }, soil: "medium", bearingCapacity: 150, groundwater: 3 }, assumptions: { houseType: "Villa", structuralSystem: "RCC Frame" }, levels: [ground], rooms, elements, layers: structuredClone(baseLayers), updatedAt: Date.now() };
}

export function cloneProject(project: HouseProject): HouseProject { return JSON.parse(JSON.stringify(project)) as HouseProject; }
export function saveProject(project: HouseProject) { localStorage.setItem(storeKey, JSON.stringify(project)); }
export function loadProject(): HouseProject | undefined { try { const raw=localStorage.getItem(storeKey); if(!raw)return undefined; const parsed=JSON.parse(raw) as HouseProject; const width=parsed.site.width??12,length=parsed.site.length??18; return { ...parsed, author: parsed.author ?? "Atharv Moon", createdAt: parsed.createdAt ?? Date.now(), site: { ...parsed.site, gridSpacing: parsed.site.gridSpacing ?? 1, snapEnabled: parsed.site.snapEnabled ?? true, workflowMode: parsed.site.workflowMode ?? "precision", shape: parsed.site.shape ?? "rectangle", corners: parsed.site.corners ?? defaultCorners(width,length), gate: parsed.site.gate ?? true, sky: parsed.site.sky ?? "clear", terrain: parsed.site.terrain ?? "level", terrainTool: parsed.site.terrainTool ?? "level", sunDirection: parsed.site.sunDirection ?? 135 } }; } catch { return undefined; } }
export function exportProject(project: HouseProject) { const blob=new Blob([JSON.stringify(project,null,2)], { type:"application/json" }); const link=document.createElement("a"); link.href=URL.createObjectURL(blob); link.download=`${project.name.toLowerCase().replace(/\s+/g,"-")}.houseforge.json`; link.click(); URL.revokeObjectURL(link.href); exportSummary(project); }
export function exportSummary(project: HouseProject) { const area=areaSchedule(project); const quantities=quantify(project); const lines=[`HOUSEFORGE PROJECT SUMMARY`, `Project: ${project.name}`, `House type: ${project.assumptions.houseType}`, `Structural system: ${project.assumptions.structuralSystem}`, `Site: ${project.site.width.toFixed(2)} m × ${project.site.length.toFixed(2)} m`, `Levels: ${project.levels.length}`, `Rooms: ${project.rooms.length}`, `Built-up area (model-derived): ${area.built.toFixed(1)} m²`, ``, `MODEL-DERIVED QUANTITY SCHEDULE`, ...quantities.map((row)=>`${row.label}: ${row.quantity} ${row.unit}`), ``, `NOTICE`, `HOUSEFORGE is an educational and conceptual environment. All design, quantity, cost, and construction outputs require independent professional verification.`].join("\n"); const blob=new Blob([lines],{type:"text/plain"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${project.name.toLowerCase().replace(/\s+/g,"-")}-summary.txt`;link.click();URL.revokeObjectURL(link.href); }

export function areaSchedule(project: HouseProject) { const plot=project.site.width*project.site.length; const rooms=project.rooms.reduce((sum,room)=>sum+room.width*room.length,0); const setbackArea=Math.max(0,(project.site.width-project.site.setbacks.left-project.site.setbacks.right)*(project.site.length-project.site.setbacks.front-project.site.setbacks.rear)); return { plot, built: rooms, carpet: rooms*0.87, open: Math.max(0,plot-setbackArea), rooms: project.rooms.length }; }
export function quantify(project: HouseProject): QuantityRow[] { const byKind=(kind: ElementKind)=>project.elements.filter((element)=>element.kind===kind); const volume=(kind: ElementKind)=>byKind(kind).reduce((sum,element)=>sum+element.dimensions[0]*element.dimensions[1]*element.dimensions[2],0); const wallArea=byKind("wall").reduce((sum,wall)=>sum+wall.dimensions[0]*wall.dimensions[1],0); const flooring=project.rooms.reduce((sum,room)=>sum+room.width*room.length,0); return [{ label:"Concrete / RCC", quantity:Number((volume("foundation")+volume("column")+volume("beam")+volume("slab")).toFixed(2)),unit:"m³",estimatedCost:0},{label:"Masonry wall area",quantity:Number(wallArea.toFixed(1)),unit:"m²",estimatedCost:0},{label:"Flooring",quantity:Number(flooring.toFixed(1)),unit:"m²",estimatedCost:0},{label:"Paintable wall area",quantity:Number((wallArea*2).toFixed(1)),unit:"m²",estimatedCost:0},{label:"Doors",quantity:byKind("door").length,unit:"no.",estimatedCost:0},{label:"Windows",quantity:byKind("window").length,unit:"no.",estimatedCost:0}]; }
export function validateProject(project: HouseProject): ProjectCheck[] { const results: ProjectCheck[]=[]; const walls=project.elements.filter((item)=>item.kind==="wall"); const columns=project.elements.filter((item)=>item.kind==="column"); const beams=project.elements.filter((item)=>item.kind==="beam"); if (!project.rooms.length) results.push({ severity:"warning",title:"No room programme",detail:"Create rooms to generate usable area, flooring, and interior schedules." }); else results.push({ severity:"pass",title:"Room programme found",detail:`${project.rooms.length} editable room${project.rooms.length===1?"":"s"} is included in the active level.` }); if (!project.elements.some((item)=>item.kind==="foundation")) results.push({ severity:"warning",title:"No foundations placed",detail:"Add foundations before interpreting the structural visualisation." }); if (beams.length && !columns.length) results.push({ severity:"error",title:"Potentially unsupported beams",detail:"Beams exist without supporting columns in the conceptual model." }); if (walls.length && !project.elements.some((item)=>item.kind==="door")) results.push({ severity:"warning",title:"No access openings",detail:"Walls are present but no door element has been placed." }); if (!project.elements.some((item)=>item.kind==="roof")) results.push({ severity:"warning",title:"Roof not defined",detail:"Add a roof system to complete the envelope." }); if (!results.some((item)=>item.severity==="error")) results.push({ severity:"pass",title:"Geometry review complete",detail:"No obvious conflicts were identified by the simplified project checker." }); return results; }
