import { Html, OrbitControls } from "@react-three/drei";
import { Canvas, useThree } from "@react-three/fiber";
import { useEffect, useLayoutEffect, useRef } from "react";
import * as THREE from "three";
import { materialColors } from "@/lib/houseforge";
import { formatLength } from "@/lib/units";
import type { FloorDisplayMode, HouseElement, HouseProject, Vec3, ViewMode } from "@/types/houseforge";

type HouseSceneProps = { project: HouseProject; selectedId?: string; view: ViewMode; timeOfDay?: number; activeLevelId?: string; floorDisplay?: FloorDisplayMode; onSelect: (id?: string) => void; };

function TerrainSurface({ site }: { site: HouseProject["site"] }) { const geometry=useRef<THREE.PlaneGeometry>(null); useEffect(()=>{const mesh=geometry.current;if(!mesh)return;const positions=mesh.attributes.position;for(let index=0;index<positions.count;index+=1){const x=positions.getX(index),z=positions.getY(index);const preset=site.terrain==="slope"?z/site.length*.32:site.terrain==="gentle"?(Math.sin(x*.55)*Math.cos(z*.38))*.12:0;const points=(site.terrainPoints??[]).reduce((height,point)=>{const distance=Math.hypot(x-point.x,z-point.z);return height+point.elevation*Math.exp(-(distance*distance)/8);},0);positions.setZ(index,preset+points);}positions.needsUpdate=true;mesh.computeVertexNormals();},[site.length,site.width,site.terrain,site.terrainPoints]);return <mesh position={[0,-.035,0]} rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry ref={geometry} args={[site.width+30,site.length+30,30,30]}/><meshStandardMaterial color="#284430" roughness={.96}/></mesh>; }

function Site({ project }: { project: HouseProject }) {
  const { width, length, setbacks, gate, sky, terrain, terrainPoints = [] } = project.site;
  const buildableWidth = Math.max(0.5, width - setbacks.left - setbacks.right);
  const buildableLength = Math.max(0.5, length - setbacks.front - setbacks.rear);
  const lineGeometry = new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-width / 2, 0.02, -length / 2), new THREE.Vector3(width / 2, 0.02, -length / 2), new THREE.Vector3(width / 2, 0.02, length / 2), new THREE.Vector3(-width / 2, 0.02, length / 2), new THREE.Vector3(-width / 2, 0.02, -length / 2)]);
  const road = project.site.road;
  const roadPosition: Vec3 = road === "north" ? [0, 0.01, length / 2 + 1.2] : road === "south" ? [0, 0.01, -length / 2 - 1.2] : road === "east" ? [width / 2 + 1.2, 0.01, 0] : [-width / 2 - 1.2, 0.01, 0];
  const roadSize: [number, number] = road === "north" || road === "south" ? [width + 5, 2.4] : [2.4, length + 5];
  const gatePosition: Vec3 = road === "north" ? [0, .8, length / 2] : road === "south" ? [0, .8, -length / 2] : road === "east" ? [width / 2, .8, 0] : [-width / 2, .8, 0];
  const gateRotation: Vec3 = road === "north" || road === "south" ? [0, 0, 0] : [0, Math.PI / 2, 0];
  return <>
    <mesh raycast={()=>null}><sphereGeometry args={[80,32,20]}/><meshBasicMaterial color={sky==="sunset"?"#72452c":sky==="overcast"?"#3d4c50":"#244a48"} side={THREE.BackSide}/></mesh>
    <mesh position={[0,-.07,0]} rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[width+54,length+54]}/><meshStandardMaterial color="#17271d" roughness={1}/></mesh>
    <TerrainSurface site={project.site} />
    {terrain==="gentle"&&<><mesh position={[-width*.32,.18,length*.3]} scale={[1,.22,1]} receiveShadow><sphereGeometry args={[3.2,24,16]}/><meshStandardMaterial color="#31583a" roughness={1}/></mesh><mesh position={[width*.42,.12,-length*.34]} scale={[1,.16,1]} receiveShadow><sphereGeometry args={[2.4,24,16]}/><meshStandardMaterial color="#31583a" roughness={1}/></mesh></>}
    {terrainPoints.map((point,index)=><group key={`${point.x}-${point.z}-${index}`} position={[point.x,Math.max(.05,point.elevation),point.z]}><mesh><sphereGeometry args={[.3,16,12]}/><meshStandardMaterial color={point.elevation>=0?"#d8a75e":"#6ba5bc"} emissive={point.elevation>=0?"#4d2f12":"#123545"} emissiveIntensity={.45}/></mesh><Html position={[0,.38,0]} center distanceFactor={16}><div className="terrain-point-tag">{point.elevation>=0?"+":""}{(point.elevation*1000).toFixed(0)} mm</div></Html></group>)}
    <gridHelper args={[Math.max(width, length) + 12, Math.max(8, Math.round((Math.max(width, length) + 12) / project.site.gridSpacing)), "#5d7674", "#233735"]} position={[0, 0, 0]} />
    <mesh rotation={[-Math.PI / 2, 0, 0]} receiveShadow><planeGeometry args={[width, length]} /><meshStandardMaterial color="#52645d" roughness={0.95} transparent opacity={0.18} /></mesh>
    <mesh position={roadPosition} rotation={[-Math.PI / 2, 0, 0]}><planeGeometry args={roadSize} /><meshStandardMaterial color="#303839" roughness={0.95} /></mesh>
    <mesh position={[0, 0.035, -length / 2 + 0.75]} rotation={[-Math.PI / 2, 0, 0]}><planeGeometry args={[2.2, 1.5]} /><meshBasicMaterial color="#b9985e" transparent opacity={0.65} /></mesh>
    <mesh position={[(setbacks.left - setbacks.right) / 2, 0.025, (setbacks.rear - setbacks.front) / 2]} rotation={[-Math.PI / 2, 0, 0]}><planeGeometry args={[buildableWidth, buildableLength]} /><meshBasicMaterial color="#79b6a0" transparent opacity={0.12} /></mesh>
    <primitive object={new THREE.Line(lineGeometry, new THREE.LineBasicMaterial({ color: "#f1be70" }))} />
    <group position={[width / 2 - 0.6, 0.03, -length / 2 + 0.8]}><mesh rotation={[-Math.PI / 2, 0, 0]}><coneGeometry args={[0.35, 0.7, 3]} /><meshBasicMaterial color="#e7d5a6" /></mesh><Html position={[0,0.2,0]} center distanceFactor={14}><div className="north-tag">N</div></Html></group>
    <Html position={[0, 0.04, -length / 2 - 0.35]} center distanceFactor={15}><div className="site-label">PLOT · {formatLength(width,project.units)} × {formatLength(length,project.units)}</div></Html>
    <Html position={[-width / 2, 0.04, -length / 2]} center distanceFactor={18}><div className="coord-tag">0,0</div></Html><Html position={[width / 2, 0.04, length / 2]} center distanceFactor={18}><div className="coord-tag">{formatLength(width,project.units)},{formatLength(length,project.units)}</div></Html>
    <Html position={roadPosition} center distanceFactor={16}><div className="road-tag">ROAD · {road.toUpperCase()} EDGE</div></Html>
    {gate&&<group position={gatePosition} rotation={gateRotation}><mesh position={[-1.35,0,0]} castShadow><boxGeometry args={[.25,1.6,.25]}/><meshStandardMaterial color="#7c6a47"/></mesh><mesh position={[1.35,0,0]} castShadow><boxGeometry args={[.25,1.6,.25]}/><meshStandardMaterial color="#7c6a47"/></mesh><mesh position={[0,.1,0]} castShadow><boxGeometry args={[2.45,1.1,.1]}/><meshStandardMaterial color="#3f5549"/></mesh><Html position={[0,1.05,0]} center distanceFactor={15}><div className="gate-tag">ENTRY GATE</div></Html></group>}
  </>;
}

function Stairs({ dimensions }: { dimensions: Vec3 }) { const [width,height,depth]=dimensions; return <group>{Array.from({length:7}).map((_,index)=><mesh key={index} position={[0,-height/2+(index+1)*height/14,-depth/2+(index+1)*depth/7.8]} castShadow><boxGeometry args={[width,height/7,depth/7]} /><meshStandardMaterial color="#8c948f" roughness={0.75} /></mesh>)}</group>; }
function RoomContext({ room, units, selected, ghost, onSelect }: { room: HouseProject["rooms"][number]; units: HouseProject["units"]; selected: boolean; ghost: boolean; onSelect: () => void }) { const color=/balcony|terrace/i.test(room.name)?"#d6b86b":/garage|utility|laundry/i.test(room.name)?"#8ea8a0":"#6da58f";return <group position={[room.x+room.width/2,.045,room.z+room.length/2]} userData={{roomId:room.id}} onPointerDown={(event)=>{event.stopPropagation();onSelect();}}><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[room.width,room.length]}/><meshStandardMaterial color={color} transparent opacity={selected?.35:ghost?.035:.12} roughness={.88}/></mesh>{selected&&<Html position={[0,.13,0]} center distanceFactor={13}><div className="object-tag">{room.name}<small>{formatLength(room.width,units)} × {formatLength(room.length,units)}</small></div></Html>}</group>; }
function WallOpening({ wall, opening, material }: { wall: HouseElement; opening: HouseElement; material: React.ReactNode }) { const [width,height,depth]=wall.dimensions; const openingWidth=Math.min(opening.dimensions[0],width*.72); const openingHeight=Math.min(opening.dimensions[1],height*.88); const side=(width-openingWidth)/2; const isDoor=opening.kind==="door"; const bottomHeight=isDoor?0:Math.max(.2,(height-openingHeight)/2); const topHeight=Math.max(.18,height-openingHeight-bottomHeight); return <>{side>.02&&<mesh position={[-(openingWidth+side)/2,0,0]} castShadow receiveShadow><boxGeometry args={[side,height,depth]} />{material}</mesh>}{side>.02&&<mesh position={[(openingWidth+side)/2,0,0]} castShadow receiveShadow><boxGeometry args={[side,height,depth]} />{material}</mesh>}{bottomHeight>.02&&<mesh position={[0,-(height-bottomHeight)/2,0]} castShadow receiveShadow><boxGeometry args={[openingWidth,bottomHeight,depth]} />{material}</mesh>}{topHeight>.02&&<mesh position={[0,(height-topHeight)/2,0]} castShadow receiveShadow><boxGeometry args={[openingWidth,topHeight,depth]} />{material}</mesh>}</>; }
function ElementMesh({ element, selected, onSelect, section, openings, ghost }: { element: HouseElement; selected: boolean; onSelect: () => void; section: boolean; openings: HouseElement[]; ghost: boolean }) {
  const group = useRef<THREE.Group>(null);
  if (section && element.position[0] > 0.5) return null;
  const color=element.color??materialColors[element.material]; const [x,y,z]=element.dimensions; const displayRotation:Vec3=element.kind==="door"&&element.doorOpen?[element.rotation[0],element.rotation[1]+Math.PI/2,element.rotation[2]]:element.rotation; const isPitchedRoof=element.kind==="roof"&&/(gable|hip|shed)/i.test(element.notes??"");
  const isLight=element.kind==="electrical"&&element.notes?.toLowerCase().includes("light");
  const material=<meshStandardMaterial color={color} roughness={element.roughness??(element.finish==="gloss"?.16:element.finish==="semi-gloss"?.35:element.finish==="satin"?.5:element.material==="glass"?.1:.7)} metalness={element.material==="steel"?0.7:0.08} transparent={element.material==="glass"||ghost} opacity={ghost?.16:element.material==="glass"?.62:1} />;
  const geometry = element.kind === "column" ? <cylinderGeometry args={[x/2,z/2,y,20]} /> : element.kind === "stair" ? null : element.kind === "landscape" ? <sphereGeometry args={[x/2,20,16]} /> : isPitchedRoof ? <coneGeometry args={[Math.max(x,z)/2,y,4]} /> : <boxGeometry args={[x,y,z]} />;
  const opening = openings.find((candidate)=>candidate.openingFor===element.id);
  return <group ref={group} position={element.position} rotation={displayRotation} userData={{ elementId: element.id }} onPointerDown={(event)=>{event.stopPropagation();onSelect();}} onDoubleClick={(event)=>{if(element.kind!=="door")return;event.stopPropagation();window.dispatchEvent(new CustomEvent("houseforge:door-toggle",{detail:element.id}));}}>
    {element.kind === "stair" ? <Stairs dimensions={element.dimensions} /> : element.kind === "wall"&&opening ? <WallOpening wall={element} opening={opening} material={material} /> : <mesh castShadow receiveShadow>{geometry}{material}</mesh>}
    {isLight&&<pointLight intensity={1.8} color={element.notes?.toLowerCase().includes("warm")?"#ffce9c":"#e3f2ff"} distance={6} decay={1.8} />}
    {selected && <lineSegments><edgesGeometry args={[new THREE.BoxGeometry(x+0.08,y+0.08,z+0.08)]} /><lineBasicMaterial color="#e5c36f" /></lineSegments>}
    {selected && <Html position={[0,y/2+0.28,0]} center distanceFactor={13}><div className="object-tag">{element.name}<small>{element.kind.toUpperCase()}{element.kind==="door"?` · ${element.doorOpen?"OPEN":"CLOSED"}`:""}</small></div></Html>}
  </group>;
}
function WalkthroughControls({ enabled, project }: { enabled: boolean; project: HouseProject }) { const { camera } = useThree(); useLayoutEffect(()=>{if(!enabled)return;camera.position.set(6.8,2.7,7.8);camera.lookAt(0,1.45,0);camera.updateProjectionMatrix();camera.updateMatrixWorld(true);},[camera,enabled]); useEffect(()=>{if(!enabled)return;const onKey=(event:KeyboardEvent)=>{const stride=event.shiftKey?1.1:.45;let nextX=camera.position.x,nextY=camera.position.y,nextZ=camera.position.z;if(event.key.toLowerCase()==="w")nextZ-=stride;if(event.key.toLowerCase()==="s")nextZ+=stride;if(event.key.toLowerCase()==="a")nextX-=stride;if(event.key.toLowerCase()==="d")nextX+=stride;if(event.key.toLowerCase()==="q")nextY-=stride;if(event.key.toLowerCase()==="e")nextY+=stride;camera.position.set(Math.min(project.site.width/2-0.35,Math.max(-project.site.width/2+0.35,nextX)),Math.min(4.2,Math.max(1.25,nextY)),Math.min(project.site.length/2-0.35,Math.max(-project.site.length/2+0.35,nextZ)));};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);},[camera,enabled,project.site.width,project.site.length]);return null; }
function SceneContents({ project, selectedId, view, timeOfDay = 12, activeLevelId, floorDisplay = "all", onSelect }: HouseSceneProps) {
  const visibleElements=project.elements.filter((element)=>project.layers[element.layer].visible).filter((element)=>floorDisplay!=="active"||element.levelId===activeLevelId).filter((element)=>view!=="walkthrough"||!(element.kind==="roof"||(element.kind==="wall"&&element.position[2]>4.7)));
  const visibleRooms=project.rooms.filter((room)=>floorDisplay!=="active"||room.levelId===activeLevelId);
  const openings=visibleElements.filter((element)=>element.kind==="door"||element.kind==="window");
  const sunPhase=(timeOfDay-6)/16*Math.PI; const daylight=Math.max(.08,Math.sin(sunPhase)); const sunAzimuth=project.site.sunDirection*Math.PI/180;
  return <group onPointerMove={(event)=>window.dispatchEvent(new CustomEvent("houseforge:scene-pointer",{detail:{x:Number(Math.min(project.site.width/2,Math.max(-project.site.width/2,event.point.x)).toFixed(2)),z:Number(Math.min(project.site.length/2,Math.max(-project.site.length/2,event.point.z)).toFixed(2))}}))}>
    <color attach="background" args={[daylight>.45?"#101d19":"#07100f"]} /><fog attach="fog" args={[daylight>.45?"#101d19":"#07100f",18,45]} />
    <ambientLight intensity={.12+daylight*.7} color={daylight>.45?"#d9e9df":"#bdc6e4"} /><directionalLight castShadow intensity={.2+daylight*2.8} color={timeOfDay>17?"#ffb675":"#ffe2b3"} position={[Math.cos(sunAzimuth)*14,4+daylight*14,Math.sin(sunAzimuth)*12]} shadow-mapSize={[1024,1024]} /><hemisphereLight intensity={.16+daylight*.45} color="#b7e2df" groundColor="#1a2b24" />
    <Site project={project} />
    {visibleRooms.map((room)=><RoomContext key={room.id} room={room} units={project.units} selected={room.id===selectedId} ghost={floorDisplay==="ghosted"&&room.levelId!==activeLevelId} onSelect={()=>onSelect(room.id)} />)}
    {visibleElements.map((element)=><ElementMesh key={element.id} element={element} selected={element.id===selectedId} section={view==="section"||view==="walkthrough"} openings={openings} ghost={(floorDisplay==="ghosted"&&element.levelId!==activeLevelId)||view==="walkthrough"} onSelect={()=>onSelect(element.id)} />)}
    <WalkthroughControls enabled={view === "walkthrough"} project={project} />
    {view !== "walkthrough" && <OrbitControls makeDefault enableDamping dampingFactor={0.08} minDistance={5} maxDistance={35} maxPolarAngle={Math.PI/2.03} target={[0,1.6,0]} />}
  </group>;
}
export function HouseScene(props: HouseSceneProps) { const isElevation=props.view==="elevation"; const isWalkthrough=props.view==="walkthrough"; return <Canvas className="house-canvas" shadows dpr={[1,1.5]} camera={{position:isElevation?[0,5,21]:isWalkthrough?[6.8,2.7,7.8]:[13,10,15],fov:isElevation?33:isWalkthrough?64:43}} gl={{antialias:true,powerPreference:"high-performance"}}><SceneContents {...props} /></Canvas>; }
